# File: config/settings.yaml
sources:
  treasury:
    provider: "FRED"
    api_key: "${FRED_API_KEY}"
  sofr:
    provider: "FRED"
  sonia:
    provider: "BankOfEngland"
  estr:
    provider: "ECB"
  repo:
    provider: "DTCC"
adjustments:
  liquidity: true
  term_premium:
    model: "ACM"
interpolation:
  method: "cubic"
